### ISSUE TITLE
Pheromone Radial Menu follows your mouse for a few seconds upon being opened

### ISSUE THREAD

**Issue by Rainbeon** [RMC-14/RMC-14#3270]
## Description
When using the new Pheromone Radial Menu, the Radial Menu will follow your mouse wherever it goes for a few seconds, trying to center the X on your mouse when you are attempting to choose a different option.

**Reproduction**
1) Press the bind to open the Pheromone Menu
2) Move the mouse in any direction once it opens

**Screenshots**
https://github.com/user-attachments/assets/977880ef-f531-48ae-8679-bb7d346679f1

**Comment by deltanedas** [comment]
fixed now that its locked to center, but this is an upstream issue with all radial menus

**Comment by Rainbeon** [comment]
> fixed now that its locked to center, but this is an upstream issue with all radial menus

It's not entirely fixed, just changed forms, as it now slides around depending on where you move
