### ISSUE TITLE
When using a well-aimed shot, a cartridge comes out of the bolt

### ISSUE THREAD

**Issue by FallingDownofMadness** [RMC-14/RMC-14#7811]
## Description
When a targeted shot is activated, a cartridge flies out of the bolt

**Reproduction**
Load any magazine into the sniper, activate the aiming shot, move away from the place where you were standing and there will be a bullet under this place

**Additional context**
This is most likely due to the fact that the aiming shot itself and the shutter release uses a unique action that is activated by default on the space bar

**Comment by XxSWAG-MASTER-OVERLORDxX** [comment]
This issue should already be fixed

**Comment by FallingDownofMadness** [comment]
No, this problem is still present, tested on the newly updated locale.

**Comment by FallingDownofMadness** [comment]
> This issue should already be fixed

No, this problem is still present
